version: '3.1'

services:
    node:
        build:
            context: .
            args:
                - NODE_ENV=development
        command: node_modules/.bin/nodemon -e html,js,css --inspect=0.0.0.0:9229
        ports:
            - 80:80
            - 5858:5858
            - 9229:9229
        volumes:
            - .:/opt/app
        environment:
            - NODE_ENV=development
            - COOKIE_HASH=gSha8kecFe2rCS8eGAughJfbwsfEEdDYykhA5QRdJjxfPK42
            - API_ROOT=/api/v1/
            - USER_API_BASE=https://aq0fp63k2b.execute-api.us-east-1.amazonaws.com/dev
            - REMOTE_API_BASE=https://2l4y9lieb3.execute-api.us-east-1.amazonaws.com/dev
            - FB_APP_ID=151031348826889
            - FB_APP_SECRET=e41bcbd13588152e8ab3d0200bdb093e
            - SOCIAL_LOGIN_REDIRECT=http://localhost/api/v1/social-login
