version: '3.1'

services:
    node:
        build:
            context: .
            args:
                - NODE_ENV=development
        command: node_modules/.bin/nodemon --inspect=0.0.0.0:9229
        ports:
            - 80:80
            - 5858:5858
            - 9229:9229
        volumes:
            - .:/opt/app
        environment:
            - NODE_ENV=development
            - API_BASE=https://iopwyeiagc.execute-api.us-east-1.amazonaws.com/dev/
            - PASS_HASH=atPVVBHNw4yfDTnPpzqCJu9BRmdQDXj4VTFwws33qrqDRp44
            - PASS_SALT_ROUNDS=10
