version: '3.1'

services:
    node:
        build:
            context: .
            args:
                - NODE_ENV=development
        ports:
            - 80:80
            - 5858:5858
            - 9229:9229
        volumes:
            - .:/opt/app
        environment:
            - NODE_ENV=development
